motion_controller:
  ros__parameters:
    cmd_vel_topic: /controller/cmd_vel
    motion_command_topic: /full_auto_rover/motion_command
    event_status_topic: /full_auto_rover/event_status
    linear_speed: 0.12
    angular_speed: 0.55
    command_timeout_sec: 0.7
    pause_on_event: true

arm_controller:
  ros__parameters:
    arm_command_topic: /full_auto_rover/arm_command
    arm_status_topic: /full_auto_rover/arm_status
    servo_topic: /servo_controller
    move_duration_sec: 0.8
    home_pose: ['10:300', '5:500', '4:210', '3:40', '2:665', '1:500']
    camera_ready_pose: ['10:300', '5:500', '4:210', '3:40', '2:665', '1:500']
    event_focus_pose: ['10:300', '5:500', '4:190', '3:70', '2:690', '1:500']
    photo_pose: ['10:300', '5:500', '4:180', '3:80', '2:700', '1:500']

mission_coordinator:
  ros__parameters:
    event_status_topic: /full_auto_rover/event_status
    aligned_topic: /full_auto_rover/event_aligned
    motion_command_topic: /full_auto_rover/motion_command
    arm_command_topic: /full_auto_rover/arm_command
    capture_trigger_topic: /full_auto_rover/capture_request
    resume_after_capture_sec: 2.0
    auto_resume: false
    auto_patrol: false
    patrol_command: forward
